### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by talantbekov123** [ai-small/validation-study-project10#1]
Отличная работа, все работает корректно. Принимаю. Похвально что учли валидацию домена с не валидными портами(http://8.8.8.8:0000). Похвально что добавили gitignore.

**Отлично**
- эфективное регулярное выражение
- оформленное readme.md
- работа на github pages, поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены

**Можно лучше**
- `review.test@yandex.ru` - В почте может присутствовать точка

**Comment by ai-small** [comment]
Спасибо! Отредактировала паттерн для почты.
